version: '3.8'
services:
  web:
    build: .
    container_name: constrent_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn rental_project.wsgi:application --bind 0.0.0.0:8000 --workers 1"
    environment:
      DJANGO_SETTINGS_MODULE: rental_project.settings
      GRAFANA_DASHBOARD_URL: http://localhost:3000/goto/df5fad9jyxddsf?orgId=1

      environment:
      DATABASE_URL: postgres://postgres:1@db:5432/rental_system_db
    ports:
      - "8000:8000"
    networks:
      - grafanaprometeus_monitoring_system
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:15
    container_name: constrent_db
    environment:
      POSTGRES_DB: rental_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - grafanaprometeus_monitoring_system

networks:
  grafanaprometeus_monitoring_system:
    external: true  

volumes:
  pgdata:
